FROM alpine:3.18 AS base1
FROM alpine:3.17 AS base2
FROM alpine:3.16 AS base3
FROM alpine:3.15 AS base4
FROM alpine:3.14 AS base5
FROM node:18-alpine AS node1
FROM node:16-alpine AS node2
FROM python:3.11-alpine AS python1
FROM python:3.10-alpine AS python2
FROM nginx:1.24-alpine AS nginx1
FROM nginx:1.23-alpine AS nginx2
FROM base1
COPY --from=base2 /etc/alpine-release /tmp/
COPY --from=base3 /etc/alpine-release /tmp/
COPY --from=base4 /etc/alpine-release /tmp/
COPY --from=base5 /etc/alpine-release /tmp/
COPY --from=node1 /usr/local/bin/node /tmp/
COPY --from=node2 /usr/local/bin/node /tmp/
COPY --from=python1 /usr/local/bin/python3 /tmp/
COPY --from=python2 /usr/local/bin/python3 /tmp/
COPY --from=nginx1 /etc/nginx /tmp/
COPY --from=nginx2 /etc/nginx /tmp/
CMD echo "stress test"

services:
  mail:
    build: .
  solr:
    build: .
  hra:
    build: .
  rio-drools-service-core:
    build: .
  rio-drools-service-epublic:
    build: .
  service1:
    build: .
  service2:
    build: .
  service3:
    build: .
  service4:
    build: .
  service5:
    build: .
  service6:
    build: .
  service7:
    build: .
  service8:
    build: .
  service9:
    build: .
  service10:
    build: .
  service11:
    build: .
  service12:
    build: .
  service13:
    build: .
  service14:
    build: .
  service15:
    build: .
